### ISSUE TITLE
Support for MacbookAir7,2 (and 7,1)

### ISSUE THREAD

**Issue by taylorthurlow** [bytbox/pommed-light#30]
Hoping to get this added to the support list. Not sure that much changed from 6,1/2.

**Comment by bytbox** [comment]
If you have access to a machine to test this on, and can make the change, I'd happily accept a pull request. I'm reluctant to make the changes without someone having done testing, which means this code pretty much only gets developed via pull requests.

**Comment by taylorthurlow** [comment]
Gotcha. I'll see what I can do about getting it working on my end. Thanks
for the quick reply!

**Comment by bytbox** [comment]
No problem :)

I suppose this is as good a time as any to mention: I no longer even use a
macbook. I still maintain this thing because... well, nobody else does, but
it always seems a bit surreal when I accept a pull request after just
reading it over, without ever having run the code myself. The pull requests
tend to be trivial copy-paste jobs, but if somebody else (wink wink nudge
nudge) was interested in taking over maintenance, I'm sure they'd be able to
do a better job.

**Comment by emx** [comment]
Hey, are you still maintaining this? Any chance to work together to enable support for MacbookAir7,1 ?

**Comment by bytbox** [comment]
I'm still around, but I'm pretty useless for anything nontrivial. I suppose it should just involved copy-pasting some code from 6,1 and 6,2. Happy to review a patch if you can make one.

**Comment by emx** [comment]
Thanks. Actually it turns out that someone already did it. And it works. I was confused because I was using my distro's pommed, not this pommed-light

**Comment by bytbox** [comment]
Well now *I'm* confused. Should this issue be closed?

**Comment by emx** [comment]
Looks like **alxndrhi** committed on 17 Jan 2017 

> Add Support Macbook Air7,2 Early 2015 (no audio)

**Comment by emx** [comment]
I confirm it works on my Macbook Air 7,1 so I guess you can close the issue.

**Comment by bytbox** [comment]
Thanks!
